name: SSH into VPS and deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy over SSH

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: pnpm-setup
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Deploy project over SSH
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            # 1. Load NVM into the session
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"

            # 2. Tell NVM to use your installed version
            nvm use v24.12.0

            # 3. Rest of your deployment logic
            if [ -d /home/repos/portfolio ]; then
              cd /home/repos/portfolio
              git pull --rebase -Xours
            else
              cd /home/repos
              git clone https://github.com/ghurtadoarevalo/portfolio.git
              cd portfolio
            fi

            pnpm install
            pnpm build
